
# Site settings
production: false
title: azk
email: azk@azukiapp.com
description: "Azk landpage project"
baseurl: ""
url: "http://www.azk.io"
twitter_username: azukiapp
github_username:  azukiapp

# Build settings
markdown: kramdown
permalink: pretty

# https://github.com/moshen/jekyll-asset_bundler
asset_bundler:
  compress:
    js: false
    css: false
  base_path: /_assets/
  server_url:
  remove_bundled: false
  dev: false
  bundle_name: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"

# https://github.com/ixti/jekyll-assets
gems: [jekyll-assets]

# #
assets:
#   js_compressor: ~
#   css_compressor: ~
#   cache: false
  cache: false
  gzip: false
  cachebust:
  baseurl: /assets/
  sources:
    - _assets

sponsors:
  gold:
    - dualtec
    - jetbrains
    - totvs
    - adtsys

  silver:
    - twitter
    - locaweb
    - buscape
    - coreos
    - docker
    - dropbox
    - evernote
    - facebook
    - google
    - mercadolivre
    - mercadopago
    - rocket
    - sendgrid
    - stripe
    - twilio

  urls:
    dualtec: http://www.dualtec.com.br/
    jetbrains: https://www.jetbrains.com/
    totvs: http://www.totvs.com/
    adtsys: http://www.adtsys.com.br/
    twitter: https://twitter.com/
    locaweb: http://www.locaweb.com.br/
    buscape: http://www.buscape.com.br/
    coreos: https://coreos.com/
    docker: https://www.docker.com/
    dropbox: https://www.dropbox.com/
    evernote: https://evernote.com
    facebook: https://www.facebook.com/
    google: https://www.google.com.br
    mercadolivre: http://www.mercadolivre.com.br/
    mercadopago: https://www.mercadopago.com.br/
    rocket: https://github.com/coreos/rocket
    sendgrid: https://sendgrid.com/
    stripe: https://stripe.com/
    twilio: https://www.twilio.com/
