
# Site settings
production: true
title: azk
email: azk@azukiapp.com
description: "Azk landpage project"
baseurl: ""
url: "http://www.azk.io"
twitter_username: azukiapp
github_username:  azukiapp

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-assets]

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: false
  gzip: false
  cachebust: hard
  baseurl: /assets/
  sources:
    - _assets


sponsors:
  gold:
    - dualtec
    - keenio

  silver:


  urls:
    dualtec: http://www.dualtec.com.br/openstack
    jetbrains: https://www.jetbrains.com/
    totvs: http://www.totvs.com/
    adtsys: http://www.adtsys.com.br/
    twitter: https://twitter.com/
    locaweb: http://www.locaweb.com.br/
    buscape: http://www.buscape.com.br/
    coreos: https://coreos.com/
    docker: https://www.docker.com/
    dropbox: https://www.dropbox.com/
    evernote: https://evernote.com
    facebook: https://www.facebook.com/
    google: https://www.google.com.br
    mercadolivre: http://www.mercadolivre.com.br/
    mercadopago: https://www.mercadopago.com.br/
    rocket: https://github.com/coreos/rocket
    sendgrid: https://sendgrid.com/
    stripe: https://stripe.com/
    twilio: https://www.twilio.com/
    keenio: http://keen.io/
