
# Site settings
production: true
title: azk
email: azk@azukiapp.com
description: "Azk landpage project"
baseurl: ""
url: "http://www.azk.io"
twitter_username: azukiapp
github_username:  azukiapp

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-assets]

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: false
  gzip: false
  cachebust: hard
  baseurl: /assets/
  sources:
    - _assets


sponsors:
  gold:
    - dualtec

  silver:
